#!/usr/bin/env bash

MPRIS_COMMAND=$1
shift
MPD_COMMAND=${1:-$MPRIS_COMMAND}
shift

if MPRIS="$(mpris-ctl list 2>&1)" && [ -n "$MPRIS" ]; then
    mpris-ctl "$MPRIS_COMMAND"
    mpcauth -q pause
else
    mpcauth -q "$MPD_COMMAND"
fi
