#!/bin/bash

MPRIS_COMMAND=$1
shift
MPD_COMMAND=${1:-$MPRIS_COMMAND}
shift

if [ -n "$(mpris-ctl list 2> /dev/null)" ]; then
    mpris-ctl "$MPRIS_COMMAND"
    mpcauth -q pause
else
    mpcauth -q "$MPD_COMMAND"
fi
