#!/bin/sh

find "$@" -type d -name ".git" -print0 \
    | $HOME/local/bin/parallel -n1 -0 'cd {//} && if git show-branch origin/master 1> /dev/null 2>&1 && ! git diff --quiet master..origin/master; then echo {//}; fi'
