#!/bin/bash

set -o errexit -o nounset -o pipefail

notify-send Notmuch Syncing...
gtk-tray-icon emblem-synchronizing &
OUTPUT="`notmuch new`"
notify-send Notmuch "$OUTPUT"
kill "$!"
if [ "$OUTPUT" != "No new mail." ]; then
    gtk-tray-icon mail-unread &
else
    gtk-tray-icon mail-read &
fi
emacsclient --eval "
(dolist (buffer '(\"${1-*notmuch-hello*}\"
                  \"*notmuch-saved-search-new*\"))
  (ignore-errors
    (with-current-buffer buffer
      (notmuch-refresh-this-buffer))))
" || true
sleep 30
kill "$!"
