#!/bin/bash

# Usage:
#   $ onclose service.log; vim service.log
#   $ onclose file_that_is_being_downloaded.mp3.part; mplayer file_that_is_being_downloaded.mp3

inotifywait -e close "$@" && sleep 0.1
