#!/usr/bin/env bash

finish() {
    rm -f "$FILE" "$NEW_FILE"
    exit
}; trap finish EXIT INT TERM

FILE="/tmp/$(date '+%Y-%m-%d-MD5HERE.png')"
set -e
if [ -n "$1" ]; then
    maim --hidecursor "$FILE"
else
    maim --hidecursor -s "$FILE"
fi
set +e

# Ensure even a very quick file save is detected.
touch -d 'second ago' "$FILE"

MTIME_OLD="$(stat -c %Y "$FILE")"
mtpaint "$FILE" || gimp "$FILE"
MTIME_NEW="$(stat -c %Y "$FILE")"

xclip -i -selection clipboard -t image/png < "$FILE"

if [ "$MTIME_OLD" != "$MTIME_NEW" ] && zenity --question --title 'Image Upload' --text 'Upload the image?'; then
    MD5=`md5sum "$FILE" | perl -naE 'say substr $F[0], 0, 6'`
    NEW_FILE="${FILE/MD5HERE/$MD5}"
    mv "$FILE" "$NEW_FILE"
    imgclip "$NEW_FILE" https://einval.eu/upload/ & disown
    while ! dumbload --no-clipboard "$NEW_FILE"; do
        if ! zenity --question --title 'Image Upload' --text 'Upload failed. Retry?'; then
            exit
        fi
    done
fi
