#!/usr/bin/env zsh

MINIBROWSER="webbroboard"
FULLBROWSER="webbroboard"

URL=$1
$=MINIBROWSER "$URL"
RESPONSE=$(curl -s -I $URL)
MIME=$(sed -n 's/^Content-Type: \([^;]*\).*/\1/ip' <<< $RESPONSE)

CODE=$(sed -n 's/^HTTP\/[.0-9]\+ \([0-9]*\) .*/\1/ip' <<< $RESPONSE)

case $CODE in
    404)
        notify-send Dispatcher "404: Not Found"
        exit 1
        ;;
esac

if [[ "$MIME" =~ 'image/' ]]; then
    notify-send Dispatcher "Image"
    exec webrun sxiv "$URL"
elif [[ "$MIME" =~ 'application/pdf' ]]; then
    notify-send Dispatcher "PDF"
    exec webrun evince "$URL"
elif [[ "$MIME" =~ 'text/plain' ]]; then
    notify-send Dispatcher "Plaintext"
    exec webrun e "$URL"
fi
